SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `rubricaDB` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `rubricaDB`;

CREATE TABLE IF NOT EXISTS `utente` (
  `Nome` varchar(30) NOT NULL,
  `Cognome` varchar(30) NOT NULL,
  `Telefono` varchar(10) NOT NULL,
  `Email` varchar(50) NOT NULL,
  PRIMARY KEY (`Telefono`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `utente` (`Nome`, `Cognome`, `Telefono`, `Email`) VALUES
('Marcello', 'Lippi', '3330011222', 'm.lippi@calcio.it'),
('Roberto', 'Donadoni', '3339900111', 'r.donadoni@calcio.it');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
